### ISSUE TITLE
绘制图形添加是否可以添加虚线的双曲线？

### ISSUE THREAD

**Issue by yuwenhui2020** [WXRIW/Ink-Canvas#10]
鼠标是否可以有拖动指针对单一笔迹进行拖动，撤回是否可以撤回多步？

**Comment by WXRIW** [comment]
多条请分多个 Issue，谢谢

**Comment by WXRIW** [comment]
虚线双曲线暂不考虑，因为绝大多数情况下用不到，主要是写起来麻烦，UI 设计也比较困难

**Comment by WXRIW** [comment]
鼠标可以点击某条墨迹，即可选中

**Comment by WXRIW** [comment]
撤销仅支持单步，多步不是很想写，希望有人能帮忙完成。

**Comment by yuwenhui2020** [comment]
虚线半椭圆（双曲线的半边）实现有难度吗，是否麻烦，这个在球体绘制中常用，虚线双曲线表达错误了，应该是半边的

**Comment by yuwenhui2020** [comment]
> 鼠标可以点击某条墨迹，即可选中

点击后无效啊，预期是为了移动单个墨迹，而且切换到鼠标直接隐藏墨迹了，不能选中墨迹

**Comment by yuwenhui2020** [comment]
> 多条请分多个 Issue，谢谢

下次一定

**Comment by yuwenhui2020** [comment]
> 虚线双曲线暂不考虑，因为绝大多数情况下用不到，主要是写起来麻烦，UI 设计也比较困难

单边的呢？

**Comment by WXRIW** [comment]
其实虚线半椭圆已经写好了，但是没有单独放出来作为一个预设图形（没位置放了）
如果要画截面圆，直接在截面圆的位置画个椭圆（用手直接画，不要用预设图形），就会自动转换为截面圆
![image](https://user-images.githubusercontent.com/62491584/146764278-2cc9cd2a-9fb2-474b-96c7-57c56e2994fd.png)
![image](https://user-images.githubusercontent.com/62491584/146764281-efbd8727-cfb7-4332-ad08-c0c95b5a6fdf.png)

**Comment by WXRIW** [comment]
> > 鼠标可以点击某条墨迹，即可选中
> 
> 点击后无效啊，预期是为了移动单个墨迹，而且切换到鼠标直接隐藏墨迹了，不能选中墨迹
![image](https://user-images.githubusercontent.com/62491584/146764365-d1606d0d-8abe-4771-ac1d-40ec1fdeb986.png)
![image](https://user-images.githubusercontent.com/62491584/146764415-037dfb68-cd16-4c1b-b9fb-d5203832b1ea.png)

**Comment by WXRIW** [comment]
不过 Ink Canvas 对鼠标支持比较差，很多优化都是只有触摸屏才有的
