### ISSUE TITLE
从Alt-Tab程序切换器隐藏窗口

### ISSUE THREAD

**Issue by kingten62b** [WXRIW/Ink-Canvas#102]
能否从Alt-Tab程序切换器隐藏窗口，
比如 https://stackoverflow.com/questions/357076/best-way-to-hide-a-window-from-the-alt-tab-program-switcher

**Comment by WXRIW** [comment]
任务视图界面目前可用于在不同桌面间切换，隐藏后将无法更换虚拟桌面。

**Comment by clover-yan** [comment]
> 任务视图界面目前可用于在不同桌面间切换，隐藏后将无法更换虚拟桌面。

@WXRIW 你并未理解他的表述。他的意思是，将 Ink Canvas 的窗口从任务视图中隐藏。

**Comment by WXRIW** [comment]
> > 任务视图界面目前可用于在不同桌面间切换，隐藏后将无法更换虚拟桌面。
> 
> @WXRIW 你并未理解他的表述。他的意思是，将 Ink Canvas 的窗口从任务视图中隐藏。
> 
> **编辑**：链接中提供了很好的解决方案，或许值得一试。

我理解了他的意思。但是当任务视图中不显示 Ink Canvas 画板时，将无法将画板移动至其他虚拟桌面。

**Comment by kingten62b** [comment]
> 任务视图界面目前可用于在不同桌面间切换，隐藏后将无法更换虚拟桌面。
“
win10可以在win+tab任务视图中将窗口设置为在每个虚拟桌面上都显示，并且虚拟桌宠模拟器在设置为”从任务切换器中隐藏窗口“后，也可以在每个虚拟桌面上都显示。

**Comment by kingten62b** [comment]
> 任务视图界面目前可用于在不同桌面间切换，隐藏后将无法更换虚拟桌面。

@WXRIW win10可以在win+tab任务视图中将窗口设置为在每个虚拟桌面上都显示，并且虚拟桌宠模拟器在设置为”从任务切换器中隐藏窗口“后，也可以会在每个虚拟桌面上都显示

**Comment by WXRIW** [comment]
> > 任务视图界面目前可用于在不同桌面间切换，隐藏后将无法更换虚拟桌面。
> 
> 
> 
> @WXRIW win10可以在win+tab任务视图中将窗口设置为在每个虚拟桌面上都显示，并且虚拟桌宠模拟器在设置为”从任务切换器中隐藏窗口“后，也可以会在每个虚拟桌面上都显示

就是为了在特定桌面上显示。举个例子，比如 Ink Canvas 碰到断点了，这是就得把 Ink Canvas 移动到另一个桌面，然后才能正常操作 Visual Studio 进行调试操作。
