### ISSUE TITLE
企图绘制焦点在 y 轴上的双曲线会导致画板不稳定

### ISSUE THREAD

**Issue by clover-yan** [WXRIW/Ink-Canvas#103]
## 复现方式
1. 开始绘制双曲线，先绘制渐近线；
2. 在渐近线相交的区域之下轻点一下，如图中 `.` 所示：  
```
\ /
 X 
/.\
```

## 复现结果
程序报错不稳定，双曲线不能被绘制；同时程序卡死，所有按钮无法点击，直到做一次面积擦除手势。

**Comment by KremeCN** [comment]
尝试了一下，我这边只做一次面积擦除不能使画板恢复正常。

**Comment by WXRIW** [comment]
我这边成功复现了这个 Bug。

**Comment by clover-yan** [comment]
@WXRIW 希望能够添加实际绘制焦点在 *y* 轴上的双曲线的功能，以解决该问题。
