### ISSUE TITLE
请问一下，为什么在触摸屏上无法使用，点画笔只是一个圈，不能画，用鼠标却可以 

### ISSUE THREAD

**Issue by netlovehf** [WXRIW/Ink-Canvas#111]
请问一下，为什么在触摸屏上无法使用，点画笔只是一个圈，不能画，用鼠标却可以

**Comment by WXRIW** [comment]
请调整设置中的特殊屏幕模式，点击矩形区域获取数值，并将上方的触摸大小倍数调整到提示的数值即可。
