### ISSUE TITLE
缩放有时过于灵敏导致使用困难

### ISSUE THREAD

**Issue by hunderlinehh** [WXRIW/Ink-Canvas#122]
我的数学老师板书的时候不太喜欢翻页，都是写完了直接往下拉继续写。在写得很多的时候，再往下拉就会越来越卡顿，甚至出现突然放大到一行只有几个字母那么大。

不过无论移动画布有多困难和迟钝，书写的时候仍然是丝滑的。

若是可以开发仅移动画布而不缩放这样的功能，也许可以大幅改善这样的情况。

**Comment by WXRIW** [comment]
已有这个功能，不过仍未发布，可等待新版发布，或使用 GitHub Actions 自动编译的版本：
https://github.com/WXRIW/Ink-Canvas/suites/18759095528/artifacts/1092792955

**Comment by WXRIW** [comment]
![image](https://github.com/WXRIW/Ink-Canvas/assets/62491584/4c976b1c-96df-4b60-921d-c2866a6e5a27)

**Comment by hunderlinehh** [comment]
> 已有这个功能，不过仍未发布，可等待新版发布，或使用 GitHub Actions 自动编译的版本：
> https://github.com/WXRIW/Ink-Canvas/suites/18759095528/artifacts/1092792955

谢谢！用 GitHub Actions 自动编译的版本提前体验了一下，整体使用体验大幅上升！☺️✨
