### ISSUE TITLE
[unimportant]页码显示文本块内容溢出

### ISSUE THREAD

**Issue by NetheriteBowl** [WXRIW/Ink-Canvas#129]
当 当前页码和总页数 均大于等于 **100** 时内容趋近于溢出（显示上已经无边距）

**Comment by clover-yan** [comment]
Not unimportant!!!

**Comment by NetheriteBowl** [comment]
> Not unimportant!!!

我觉得较其他ISSUE而言这个不算重要或者严重，所以写了unimportant

**Comment by NetheriteBowl** [comment]
在某电脑 1600x900分辨率下已经溢出的截图
![截图 2024-03-03](https://github.com/WXRIW/Ink-Canvas/assets/75211294/b7e417db-a0c9-41f3-8c4a-6d89012e44f3)
