### ISSUE TITLE
添加更多对鼠标的支持？

### ISSUE THREAD

**Issue by jiajiaxd** [WXRIW/Ink-Canvas#13]
如画板模式下鼠标滚轮翻页、双键同时按可以双指手势等..

**Comment by jiajiaxd** [comment]
另外有个bug，在鼠标使用下选择克隆的功能无效

**Comment by WXRIW** [comment]
目前不打算针对鼠标进行优化，因为我们学校的白板都是触摸屏，很少有班级使用鼠标，所以暂时不考虑
鼠标模式下选择墨迹后很多功能都会失效

**Comment by WXRIW** [comment]
鼠标的优化等我考完试看情况，如果有时间可以考虑优化的，这个 Issue 不关

**Comment by jiajiaxd** [comment]
好的
