### ISSUE TITLE
WPS Office不会进入PPT模式

### ISSUE THREAD

**Issue by apoint123** [WXRIW/Ink-Canvas#135]
在学校的多台电脑测试，用WPS Office放映文件时Ink Canvas均不会进入PPT模式，还是说WPS Office不能兼容？

**Comment by kengwang** [comment]
对于 WPS 的适配仅为测试, 不能保证对 WPS 各个版本的适配, 此 Issue 不会被进一步处理

**Comment by WXRIW** [comment]
这个是 WPS 的问题，不是 Ink Canvas 的问题，需要由用户自行解决。您还可以尝试与金山公司取得联系以获取帮助。

最简单的方法，建议您安装并使用 Microsoft Office。

**Comment by clover-yan** [comment]
@apoint123 请尝试打开`开始菜单` --> `WPS Office` --> `配置工具`，点击`高级`，并启用与 Microsoft Office 兼容的相关选项。

注意，如果安装了 Microsoft Office，这会导致 Microsoft Office 不能和 Ink Canvas 共同使用。
