### ISSUE TITLE
[unimportant] 批注模式工具栏的备选墨迹颜色色系会随黑/白板切换而改变

### ISSUE THREAD

**Issue by KremeCN** [WXRIW/Ink-Canvas#136]
该问题不存在于 Release 版本，而存在于[该 Action Build 版本](https://github.com/WXRIW/Ink-Canvas/actions/runs/8277516470)。

## 复现步骤
1. 打开设置界面
2. 进入批注模式
3. 将`使用白板 (白色背景)`选项由打开状态关闭，观察到批注工具栏的备选墨迹颜色更改为亮色系
4. 此时如果退出批注模式再次进入，备选墨迹颜色恢复为暗色系

## 预期行为
批注模式的工具栏备选墨迹颜色不随`使用白板 (白色背景)`选项而改变。

![bandicam 2024-03-18 18-40-09-203](https://github.com/WXRIW/Ink-Canvas/assets/63275597/4467f757-4eb1-4a69-9c17-06e004d04006)

**Comment by clover-yan** [comment]
设置界面本就不该在批注模式下访问。
