### ISSUE TITLE
抽签功能不正常工作

### ISSUE THREAD

**Issue by CN-Ironegg** [WXRIW/Ink-Canvas#14]
我们班共有50人，刚开始抽正常，可是后面会重复抽取前面所抽过的人（甚至3次是同一个人），希望改为“不放回抽样”🙂

**Comment by WXRIW** [comment]
是的，这是新版本加入的bug，目前的解决方案是随便画一笔再抽（每画一笔都会根据墨迹生成一个新的随机种子）
目前已修复（还原成了之前的抽奖策略），但是未发布，可以直接编译源码来使用修复后的版本。

**Comment by jiajiaxd** [comment]
使用实时的时间戳作为随机种子是否更加合适？

**Comment by WXRIW** [comment]
旧版本使用的是时间，新版使用的是笔画种子+时间，但是有问题

**Comment by CN-Ironegg** [comment]
哦，我明白了
