### ISSUE TITLE
触屏时笔变为橡皮擦 而用鼠标时正常

### ISSUE THREAD

**Issue by wangwentao737** [WXRIW/Ink-Canvas#146]
触屏时笔变为橡皮擦 而用鼠标时正常

**Comment by clover-yan** [comment]
能不能看一下 README？写得清清楚楚，**打开特殊屏幕模式就行了**！都来发 Issue 了也不看一看 README？用你发 Issue 的时间我能看五遍 README，看完了难道还不知道是什么问题？
