### ISSUE TITLE
功能需求：添加进入鸿合板书精灵后自动隐藏选项

### ISSUE THREAD

**Issue by Jursin** [WXRIW/Ink-Canvas#149]
功能需求：添加进入鸿合板书精灵后自动隐藏选项

**Comment by clover-yan** [comment]
感谢你的建议！但是，由于技术限制或产品设计的原因，目前无法实现“进入鸿合板书精灵后自动隐藏选项”这一功能。我们会将你的需求反馈给相关团队，供未来版本考虑。非常感谢你的理解和支持！

**Comment by Jursin** [comment]
> 不应该在ic这里提这种issue，首先ic就没有“自动隐藏”这个功能。建议去ica下面提issue。

哦哦，好的
