### ISSUE TITLE
反馈：鸿合一体机上Ink-Canvas与Wallpaper Engine同时运行时会导致Wallpaper壁纸卡死

### ISSUE THREAD

**Issue by GreenBudsOnPotato** [WXRIW/Ink-Canvas#152]
系统环境：Windows 10 Professional
一体机品牌：HiteVision鸿合
硬件配置：如果需要知道请留言，暂未作记录
问题描述：当Ink-Canvas与Wallpaper Engine同时运行时，会导致动态壁纸卡死，但Wallpaper程序本身正常（设置，更改壁纸什么的都可以用）
当Ink-Canvas退出运行后，Wallpaper壁纸恢复正常。
Ink-Canvas貌似不受Wallpaper影响。

**Comment by STBBRD** [comment]
![image](https://github.com/user-attachments/assets/2e37e4a2-3688-4674-94a9-29cee6773455)
![image](https://github.com/user-attachments/assets/53f1c8c3-ab44-4f08-b8da-f75ad3546a26)

**Comment by clover-yan** [comment]
@GreenBudsOnPotato Ink Canvas 是全屏应用，无论当前状态和场景如何。请尝试调节 Wallpaper Engine 内有关全屏应用自动暂停的设置项。

@STBBRD 和专注模式应该没有关系。

**Comment by GreenBudsOnPotato** [comment]
问题已解决，属于Wallpaper Engine设置的问题，感谢各位
