### ISSUE TITLE
翻页笔（类似于USB键盘）失灵

### ISSUE THREAD

**Issue by CN-Ironegg** [WXRIW/Ink-Canvas#17]
- [x]  当Ink-Canvas置于窗口**顶层**时，会导致_Powerpoint_无法检测翻页笔信号正确**翻页**，希望能加入对键盘信号做出反应的功能。
---2022/4/24---
（第二项的小问题已经用VS重写解决）
翻页笔的基本按键：
向左箭头 上一张
向右箭头 下一张
ESC  结束放映

**Comment by WXRIW** [comment]
抱歉才看到，ink canvas支持左右箭头翻页，但是不支持esc退出，这个暑假加入

**Comment by WXRIW** [comment]
放映自动进入笔功能，这个是一直都支持的
![image](https://user-images.githubusercontent.com/62491584/164984866-d2a9150d-0eed-4a63-a526-04ed1b45c674.png)

**Comment by CN-Ironegg** [comment]
> 放映自动进入笔功能，这个是一直都支持的 ![image](https://user-images.githubusercontent.com/62491584/164984866-d2a9150d-0eed-4a63-a526-04ed1b45c674.png)

之前没看到这个功能🤡，感谢您从百忙之中抽空回答，辛苦了！祝考试顺利U•ェ•*U

**Comment by CN-Ironegg** [comment]
这个问题貌似仍然没有解决，或许大概可能该试试**“PgUp”**上和**“PgDn”**下

**Comment by CN-Ironegg** [comment]
我可能需要说声抱歉，之前提交时我也许没有彻底弄清翻页笔的工作原理（种类品牌太多了，不太了解）

**Comment by YujunA** [comment]
翻页笔的工作原理一般都是在按下翻页按钮的时候模拟键盘按下键盘按键（如p，n，pageup，pagedown，方向键，ctrl+p进入画笔模式，ctrl+e橡皮擦模式，esc退出等）。其实只要在主窗口中的键盘按下事件中处理一下就可以了。

**Comment by YujunA** [comment]
虽然这个问题自己就能解决，但是每次发布更新之后我都要重新编译一遍，挺麻烦。另外学校教室的白板电脑撑不下庞大的visual studio。

**Comment by CN-Ironegg** [comment]
> 虽然这个问题自己就能解决，但是每次发布更新之后我都要重新编译一遍，挺麻烦。另外学校教室的白板电脑撑不下庞大的visual studio。

我们学校电脑倒是撑得住，而且我也曾也成功在mainwin里面写了，不过问题是30天试用期后我不敢在学校电脑上登邮箱获取许可证。而且和你一样，每次编译，尤其是在触屏电脑上操作极为麻烦，而我自己的win7电脑配置还没有学校高，再加上两台电脑的.net运行时问题非常头疼

**Comment by YujunA** [comment]
> > 虽然这个问题自己就能解决，但是每次发布更新之后我都要重新编译一遍，挺麻烦。另外学校教室的白板电脑撑不下庞大的visual studio。
> 
> 我们学校电脑倒是撑得住，而且我也曾也成功在mainwin里面写了，不过问题是30天试用期后我不敢在学校电脑上登邮箱获取许可证。而且和你一样，每次编译，尤其是在触屏电脑上操作极为麻烦，而我自己的win7电脑配置还没有学校高，再加上两台电脑的.net运行时问题非常头疼
> 

太对了！希望这个问题能尽快解决

**Comment by jiajiaxd** [comment]
已经提交pr
在作者发布新的release之前可以暂时用此exe文件替换
[Ink Canvas.zip](https://github.com/WXRIW/Ink-Canvas/files/9035017/Ink.Canvas.zip)
支持了p和n

**Comment by CN-Ironegg** [comment]
![picsss.PNG](https://pic.rmb.bdstatic.com/bjh/e62ef6b70c28ffc0cc81a9ebfe7a354c.png)

兄弟们，我找到了一个更全的快捷键列表，这 **几乎** 覆盖所有翻页笔
详见：[https://support.microsoft.com/en-us/office/use-keyboard-shortcuts-to-deliver-powerpoint-presentations-1524ffce-bd2a-45f4-9a7f-f18b992b93a0](url) 
### 祝Ink Canvas越来越好 _（干翻希某[误]）_

**Comment by YujunA** [comment]
> ![picsss.PNG](https://pic.rmb.bdstatic.com/bjh/e62ef6b70c28ffc0cc81a9ebfe7a354c.png)
> 
> 兄弟们，我找到了一个更全的快捷键列表，这 **几乎** 覆盖所有翻页笔
> 详见：[https://support.microsoft.com/en-us/office/use-keyboard-shortcuts-to-deliver-powerpoint-presentations-1524ffce-bd2a-45f4-9a7f-f18b992b93a0](url) 
> ### 祝Ink Canvas越来越好 _（干翻希某[误]）_

确实，希沃laji

**Comment by WXRIW** [comment]
怀疑就是p和n，从来没用过这两个键翻页

**Comment by YujunA** [comment]
> 怀疑就是p和n，从来没用过这两个键翻页

不同品牌的翻页笔按键会不一样，建议把微软官方所说明的按键都顾及到

**Comment by YujunA** [comment]
![QQ截图20220710215353.png](https://user-images.githubusercontent.com/54567489/178147923-b1cdd9e4-e847-4a17-a21f-abc4dd122a57.png)![QQ截图20220710215359.png](https://user-images.githubusercontent.com/54567489/178147935-c8a71611-cc75-47bd-a88b-47f37aba9b30.png)![QQ截图20220710215405.png](https://user-images.githubusercontent.com/54567489/178147936-4d113ce7-1e3b-4774-848e-3dc6f4382f58.png)![QQ截图20220710215409.png](https://user-images.githubusercontent.com/54567489/178147943-41c6ff54-dffa-472b-91e3-3e21343d6b65.png)![QQ截图20220710215403.png](https://user-images.githubusercontent.com/54567489/178147945-ce851ffb-b1dd-4521-bdcb-5043924315e2.png)

**Comment by jiajiaxd** [comment]
发现一个很奇怪的现象
在自己电脑测试时是没问题的
但是如果是在学校 用触摸把画板打开（此时电脑上没插键盘） 写几笔
然后再插上键盘 什么按键也识别不到
而翻页笔的使用场景基本与这个类似
会不会是使用触摸写字的时候焦点并不在主程序上？

**Comment by YujunA** [comment]
> 发现一个很奇怪的现象
> 在自己电脑测试时是没问题的
> 但是如果是在学校 用触摸把画板打开（此时电脑上没插键盘） 写几笔
> 然后再插上键盘 什么按键也识别不到
> 而翻页笔的使用场景基本与这个类似
> 会不会是使用触摸写字的时候焦点并不在主程序上？

一般写完字之后焦点就会在inkcanvas上

**Comment by jiajiaxd** [comment]
> > 发现一个很奇怪的现象
> > 在自己电脑测试时是没问题的
> > 但是如果是在学校 用触摸把画板打开（此时电脑上没插键盘） 写几笔
> > 然后再插上键盘 什么按键也识别不到
> > 而翻页笔的使用场景基本与这个类似
> > 会不会是使用触摸写字的时候焦点并不在主程序上？
> 
> 一般写完字之后焦点就会在inkcanvas上

我不确定是不是因为我们班电脑有问题
请问一下你那边有没有做过此类测试，会不会出问题？

**Comment by YujunA** [comment]
> > > 发现一个很奇怪的现象
> > > 在自己电脑测试时是没问题的
> > > 但是如果是在学校 用触摸把画板打开（此时电脑上没插键盘） 写几笔
> > > 然后再插上键盘 什么按键也识别不到
> > > 而翻页笔的使用场景基本与这个类似
> > > 会不会是使用触摸写字的时候焦点并不在主程序上？
> > 
> > 一般写完字之后焦点就会在inkcanvas上
> 
> 我不确定是不是因为我们班电脑有问题
> 请问一下你那边有没有做过此类测试，会不会出问题？

我们放假前一直用的都是以前很旧的版本（那个时候还没有这个功能），要不我明天用自己电脑试试？

**Comment by jiajiaxd** [comment]
好的（苦逼高中狗还没放假呜呜呜）



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月10日(周日) 晚上10:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [WXRIW/Ink-Canvas] 翻页笔（类似于USB键盘）失灵 (Issue #17)




    
发现一个很奇怪的现象
 在自己电脑测试时是没问题的
 但是如果是在学校 用触摸把画板打开（此时电脑上没插键盘） 写几笔
 然后再插上键盘 什么按键也识别不到
 而翻页笔的使用场景基本与这个类似
 会不会是使用触摸写字的时候焦点并不在主程序上？
  
一般写完字之后焦点就会在inkcanvas上
  
我不确定是不是因为我们班电脑有问题
 请问一下你那边有没有做过此类测试，会不会出问题？
  
我们放假前一直用的都是以前很旧的版本（那个时候还没有这个功能），要不我明天用自己电脑试试？

**Comment by YujunA** [comment]
> 好的（苦逼高中狗还没放假呜呜呜）
> 
> 
> 
> ---原始邮件---
> 发件人: ***@***.***&gt;
> 发送时间: 2022年7月10日(周日) 晚上10:54
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.******@***.***&gt;;
> 主题: Re: [WXRIW/Ink-Canvas] 翻页笔（类似于USB键盘）失灵 (Issue #17)
> 
> 
> 
> 
>     
> 发现一个很奇怪的现象
>  在自己电脑测试时是没问题的
>  但是如果是在学校 用触摸把画板打开（此时电脑上没插键盘） 写几笔
>  然后再插上键盘 什么按键也识别不到
>  而翻页笔的使用场景基本与这个类似
>  会不会是使用触摸写字的时候焦点并不在主程序上？
>   
> 一般写完字之后焦点就会在inkcanvas上
>   
> 我不确定是不是因为我们班电脑有问题
>  请问一下你那边有没有做过此类测试，会不会出问题？
>   
> 我们放假前一直用的都是以前很旧的版本（那个时候还没有这个功能），要不我明天用自己电脑试试？
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***&gt;

真的高中难得放假，我明天起来再试试

**Comment by YujunA** [comment]
> 发现一个很奇怪的现象
> 在自己电脑测试时是没问题的
> 但是如果是在学校 用触摸把画板打开（此时电脑上没插键盘） 写几笔
> 然后再插上键盘 什么按键也识别不到
> 而翻页笔的使用场景基本与这个类似
> 会不会是使用触摸写字的时候焦点并不在主程序上？

我们老师一般早上就会把翻页笔的接收器插在电脑里，然后一整天都不动，偶尔晚上看见了就取下来。

**Comment by WXRIW** [comment]
> > 发现一个很奇怪的现象
> > 在自己电脑测试时是没问题的
> > 但是如果是在学校 用触摸把画板打开（此时电脑上没插键盘） 写几笔
> > 然后再插上键盘 什么按键也识别不到
> > 而翻页笔的使用场景基本与这个类似
> > 会不会是使用触摸写字的时候焦点并不在主程序上？
> 
> 一般写完字之后焦点就会在inkcanvas上

我等会检查下，ink canvas针对焦点问题是有优化的

**Comment by WXRIW** [comment]
我想了一下，Ink Canvas 如果接收到翻页的按键操作，会自动调用 PowerPoint 的翻页，并且自动将焦点转移到 PowerPoint 上

**Comment by CN-Ironegg** [comment]
> 发现一个很奇怪的现象 在自己电脑测试时是没问题的 但是如果是在学校 用触摸把画板打开（此时电脑上没插键盘） 写几笔 然后再插上键盘 什么按键也识别不到 而翻页笔的使用场景基本与这个类似 会不会是使用触摸写字的时候焦点并不在主程序上？

感同身受，我用希沃自带的红外遥控也是这样，用这玩意[https://keycode.info/](https://keycode.info/)给它一检测就是PageUp和Down，但仍然翻不了

> 好的（苦逼高中狗还没放假呜呜呜）

一样呜呜呜，22号放到下个月15号（但是也许可以利用这段时间避开摄像头[关网络]测试一下，，）

**Comment by YujunA** [comment]
自己电脑（w11，台式，非触屏）试一切正常，一放到班上（w8.1）就容易出问题。
