### ISSUE TITLE
建议添加开关控制是否可以通过单击屏幕其他地方自动删除正在书写的墨迹

### ISSUE THREAD

**Issue by YujunA** [WXRIW/Ink-Canvas#20]
我们老师在书写的时候，经常没松手时衣服碰到屏幕的其他地方，然后整个笔画就没了。这个类似撤销的功能有时候挺方便，但是希望能添加一个开关控制。（老师已经吐槽过很多遍了）

**Comment by WXRIW** [comment]
这是因为衣服碰到屏幕的时候，相当于第二根手指碰到屏幕，会自动进入缩放模式，并清除上一笔墨迹

**Comment by YujunA** [comment]
> 这是因为衣服碰到屏幕的时候，相当于第二根手指碰到屏幕，会自动进入缩放模式，并清除上一笔墨迹

我看设置面板里的选项有点杂乱，不知道有没有可以关闭自动缩放的地方呢

**Comment by WXRIW** [comment]
暂时没有，有空加
