### ISSUE TITLE
翻页笔在纯触控使用场景下会出现问题

### ISSUE THREAD

**Issue by jiajiaxd** [WXRIW/Ink-Canvas#22]
经过测试，
在纯触控操作下写字，貌似焦点并不在Ink Canvas上，此时检测不到任何键盘按键。
但是，如果用鼠标写一笔，就可以获取到键盘按键。
这貌似是Windows触控机制的问题，目前不知道该如何解决（主要是家里没支持触控的电脑）...

**Comment by YujunA** [comment]
> 经过测试，
> 在纯触控操作下写字，貌似焦点并不在Ink Canvas上，此时检测不到任何键盘按键。
> 但是，如果用鼠标写一笔，就可以获取到键盘按键。
> 这貌似是Windows触控机制的问题，目前不知道该如何解决（主要是家里没支持触控的电脑）...
> 

之前在学校里也这样，家里没触屏不好测试

**Comment by jiajiaxd** [comment]
是不是可以尝试在检测到ink canvas被点击后强制获得焦点？比如，点击笑脸，写字什么的，加一行强制获取焦点的代码？

**Comment by YujunA** [comment]
> 是不是可以尝试在检测到ink canvas被点击后强制获得焦点？比如，点击笑脸，写字什么的，加一行强制获取焦点的代码？
> 可以参考这里
> https://stackoverflow.com/questions/10898560/how-to-set-focus-to-another-window

按道理来说焦点在ppt上的时也能够正常翻页的

**Comment by WXRIW** [comment]
焦点在ink canvas上还是powerpoint上，都可以正常翻页的

**Comment by WXRIW** [comment]
触摸后焦点是会转移到 Ink Canvas 上的

**Comment by jiajiaxd** [comment]
离谱，那是什么缘故导致的此问题呢？



---原始邮件---
发件人: "XY ***@***.***&gt;
发送时间: 2022年7月12日(周二) 中午12:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [WXRIW/Ink-Canvas] 翻页笔在纯触控使用场景下会出现问题 (Issue #22)




 
焦点在ink canvas上还是powerpoint上，都可以正常翻页的

**Comment by YujunA** [comment]
> 离谱，那是什么缘故导致的此问题呢？
> 
> 
> 
> ---原始邮件---
> 发件人: "XY ***@***.***&gt;
> 发送时间: 2022年7月12日(周二) 中午12:06
> 收件人: ***@***.***&gt;;
> 抄送: ***@***.******@***.***&gt;;
> 主题: Re: [WXRIW/Ink-Canvas] 翻页笔在纯触控使用场景下会出现问题 (Issue #22)
> 
> 
> 
> 
>  
> 焦点在ink canvas上还是powerpoint上，都可以正常翻页的
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你用的啥系统？

**Comment by jiajiaxd** [comment]
win10 ltsc 2021 按理说跟系统没关系



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月13日(周三) 下午3:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [WXRIW/Ink-Canvas] 翻页笔在纯触控使用场景下会出现问题 (Issue #22)




  
离谱，那是什么缘故导致的此问题呢？
 
---原始邮件---
 发件人: "XY @.&gt;
 发送时间: 2022年7月12日(周二) 中午12:06
 收件人: @.&gt;;
 抄送: @.@.&gt;;
 主题: Re: [WXRIW/Ink-Canvas] 翻页笔在纯触控使用场景下会出现问题 (Issue #22)
 
焦点在ink canvas上还是powerpoint上，都可以正常翻页的
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you authored the thread.Message ID: @.***&gt;
  
你用的啥系统？

**Comment by YujunA** [comment]
> win10 ltsc 2021 按理说跟系统没关系

以前学校用的w7和8.1都没有明显问题

**Comment by CN-Ironegg** [comment]
实测，使用**Windows10**，焦点在Ink-canvas上时仍无法翻页（使用希沃配套遥控器，[Keycode](https://keycode.info/) 检测出来的是PageUp），但焦点在Powerpoint上时正常。

**Comment by jiajiaxd** [comment]
> 实测，使用**Windows10**，焦点在Ink-canvas上时仍无法翻页（使用希沃配套遥控器，[Keycode](https://keycode.info/) 检测出来的是PageUp），但焦点在Powerpoint上时正常。

其实如果有鼠标的话，用鼠标点一下ink canvas就能正常翻页了
感觉是windows某种机制

**Comment by CN-Ironegg** [comment]
> 

1.问题是学校没有鼠标
2.看到一篇文章，不知道有没有用，先贴上：[csdn](https://blog.csdn.net/qq_28368039/article/details/103677419)
3.另外，有些软件即使在后台也能检测快捷键，可能可以参考一下（但是如果Powerpoint和Ink-Canvas一起翻页就坏了）![Coolapk-LHHJ](https://coolemotion.netlify.app/source/png/c-liuhanhuaji.png)

**Comment by WXRIW** [comment]
才看到，在后台检测快捷键就涉及到注册系统快捷键，首先，报毒几率增大，因为需要有全局键盘钩子，其次，容易引出其他问题，可以尝试一下用2中的文章里的解决方案

**Comment by WXRIW** [comment]
最新 Commit 应该修复了，各位测试后反馈一下哈

**Comment by jiajiaxd** [comment]
我用手机spacedesk连电脑后进行测试，没有问题

**Comment by CN-Ironegg** [comment]
可以了，在希沃用自带遥控器上测试的

**Comment by WXRIW** [comment]
好，那这个issue就先关闭了
