### ISSUE TITLE
在鼠标环境内无法克隆（即选中并复制必要的图形）

### ISSUE THREAD

**Issue by 2b-creator** [WXRIW/Ink-Canvas#26]
我尝试画了一些奇怪的东西，选中后克隆无法像希沃白板5一样复制（使用VMware虚拟机建立的Seewo Windows 10 内置系统，直接向厂家提供sn号发送过来的gho文件

**Comment by WXRIW** [comment]
不支持鼠标，仅支持触摸

**Comment by 2b-creator** [comment]
好的，只能回学校再试试了
