### ISSUE TITLE
建议增加幻灯片浏览定位功能

### ISSUE THREAD

**Issue by LinAhui** [WXRIW/Ink-Canvas#27]
非常好用，如果能加入象101教育PPT一样，演示的过程中，可以浏览并定位到任意一张幻灯片的功能就更好了。

**Comment by WXRIW** [comment]
目前可以通过：  
1. 隐藏画板
2. 双指手势打开幻灯片缩略图
3. 双击切换

**Comment by CN-Ironegg** [comment]
> 目前可以通过：
> 
>     1. 隐藏画板
> 
>     2. 双指手势打开幻灯片缩略图
> 
>     3. 双击切换

他可能说的是在翻页箭头中间添加一个方框以显示页码，点击页码弹出竖条缩略图列表（类似PPT编辑模式左边一栏）

**Comment by LinAhui** [comment]
> > 目前可以通过：
> > ```
> > 1. 隐藏画板
> > 
> > 2. 双指手势打开幻灯片缩略图
> > 
> > 3. 双击切换
> > ```
> 
> 他可能说的是在翻页箭头中间添加一个方框以显示页码，点击页码弹出竖条缩略图列表（类似PPT编辑模式左边一栏）

是的，教学过程中，有时需要回到之前某张幻灯片，点一下出现缩略图列表（最好左右两边下角都有），切换非常方便。

双指手势打开缩略图，之前没试过，不太了解手势操作，回来再试试。

**Comment by WXRIW** [comment]
可以试试看，那个是 PowerPoint 自带的缩略图，Ink Canvas 如果需要调用缩略图的话，代码量有点大，我现在开学比较忙，还有另一个项目要弄，没时间弄

**Comment by kengwang** [comment]
这个功能我可能会尝试进行实现

**Comment by kengwang** [comment]
![image](https://user-images.githubusercontent.com/30862240/216804885-dc8bbe8b-76de-49da-a374-163f6851ac18.png)

大致初步的效果

**Comment by kengwang** [comment]
https://user-images.githubusercontent.com/30862240/216805668-ef5ce2d3-464b-4f0c-954e-983c1035bc05.mp4

大致效果

**Comment by aniketpotdar425** [comment]
@kengwang I would like to have this feature too, please help me with the code that you have implemented.
