### ISSUE TITLE
建议增加文档保存功能

### ISSUE THREAD

**Issue by brandtop** [WXRIW/Ink-Canvas#31]
1.建议增加Ink-Canvas的文档保存功能，便于下次查看沟通（目前可以进行截图或保存单页面的墨迹，需要整个文档的保存）。
2.建议增加工具栏的上、下、左、右位置设置，有时候放到侧面操作起来会更方便。
3.建议撤销返回功能可以设置多次。
非常感谢您的付出。

**Comment by WXRIW** [comment]
1. PowerPoint 目前 Ink Canvas 是支持所有幻灯片的墨迹保存的，但白板暂不支持
2. 侧面不太好弄，需要改动的代码有点多，量稍大，您可以按住笑脸把控制悬浮窗拖动到您想放置的地方（2.x 的控制工具栏是在两侧的，您可以尝试这个旧版本
3 这个我也想做，但是当时有点懒也没太多时间，就没弄了，后续应该会有开发者完善这个功能

**Comment by CN-Ironegg** [comment]
白板加个导出 _pdf_ 会很香

**Comment by kengwang** [comment]
Reopen #31

> 3.建议撤销返回功能可以设置多次。
可能会试着弄弄
