### ISSUE TITLE
部分配置下 3.4, 3.5 版本无法启动

### ISSUE THREAD

**Issue by brandtop** [WXRIW/Ink-Canvas#33]
1.问题反馈：3.4版本安装正常，启动后无任何可操作界面。再次启动无反应。系统版本 win11 22h2（重新安装3.3版本运行正常，3.4没反应）
2 小建议：可以记录工具栏启动位置（设置为随win启动，习惯放到左下角或右下角，每次重新启动都需要拖到位置）
非常感谢，辛苦了。

**Comment by WXRIW** [comment]
我也遇到了同样的问题，准备调查导致原因

**Comment by WXRIW** [comment]
目前已经定位到本问题是由 Office 导致的，目前可以通过安装 Microsoft Office 来解决。

**Comment by 26560** [comment]
> 

同样打开后无任何界面,但是根本没装Microsoft Office.有没有点头绪

**Comment by WXRIW** [comment]
去装Office，就可以用了。或者暂时用 3.2.4 或更早的版本

**Comment by 26560** [comment]
> 去装Office，就可以用了。或者暂时用 3.2.4 或更早的版本

好的我回去试试谢谢

**Comment by WXRIW** [comment]
已修复，下版本将恢复无 Office 环境下的运行，请坐和放宽，好东西就要来了。
