### ISSUE TITLE
建议增加文本工具（在屏幕上打字）

### ISSUE THREAD

**Issue by Jason-XII** [WXRIW/Ink-Canvas#37]
您好！Ink Canvas目前只能够用鼠标（或者手写板）在屏幕上进行写画，而有时候如果能够在屏幕上直接打字会更加方便。比如我选择“文本输入”之后，按屏幕的任意一处，然后就可以在那里开始打字。请问这个打字输入的功能能否在未来的Ink Canvas版本中实现？谢谢！

**Comment by WXRIW** [comment]
本软件是为白板设计的，键鼠考虑较少，所以只提供基本支持
