### ISSUE TITLE
给产品的几个建议

### ISSUE THREAD

**Issue by jiajiaxd** [WXRIW/Ink-Canvas#4]
1.希望截图时可以自动隐藏左右的按钮
2.抽奖功能的导入名单不会检测导入的是否正确，若错误会导致软件闪退
3.计时器功能希望在计时时 可以缩小成一个小窗口 显示剩余时间

**Comment by WXRIW** [comment]
感谢建议！
1. 下版本加入（设置中提供隐藏的选项）
2. 不知道是否是已经修复的 bug，因为在发布最新版后的几个小时内修复了几个关于抽奖的 bug
3. 最好给个概念图看下，因为这个计时器是几乎 1:1 复刻 Win 11 的计时器的，所以看情况，可能加入。

**Comment by jiajiaxd** [comment]
概念图大概是这个样子的 在闲置了5秒后自动缩小成这个样子（画图技术差）
![image](https://user-images.githubusercontent.com/51043917/140610756-30732b89-1701-4b7a-8770-a78c12c725a8.png)

**Comment by WXRIW** [comment]
就是自动按比例变小吗

**Comment by jiajiaxd** [comment]
嗯嗯 然后是置顶的 不知道可不可以加 不能加也无所谓

**Comment by WXRIW** [comment]
不过缩小只会也没什么用处，因为计时器打开的时候是不能操作画板其他功能的

**Comment by jiajiaxd** [comment]
那好吧 无所谓的

**Comment by WXRIW** [comment]
目前已经是置顶的了

**Comment by WXRIW** [comment]
新版 UI 大改，控制栏变得很小，还需要隐藏这个功能吗，因为写起来有些麻烦

**Comment by jiajiaxd** [comment]
最好有 = = 无所谓的啦

**Comment by kengwang** [comment]
> 3.计时器功能希望在计时时 可以缩小成一个小窗口 显示剩余时间

这个功能将会实现

**Comment by kengwang** [comment]
![image](https://user-images.githubusercontent.com/30862240/218270918-7214bd59-ea2a-4cf5-bb0a-75fdad33608e.png)

预计效果
