### ISSUE TITLE
建议为工具条的按钮增加反馈效果

### ISSUE THREAD

**Issue by YujunA** [WXRIW/Ink-Canvas#41]
如题，建议为工具条的按钮增加悬停，按下，选中反馈效果（实在不行可以不做动画，只要能让用户知道这个按钮有没有点进去，有没有选中）。之前我们老师点了橡皮按钮之后发现还是在写字（可能是没点中），老师已经不止一次和我们提过这个问题了，希望可以改进，谢谢！

**Comment by WXRIW** [comment]
好提议，但是一直没做。
目前可以看下方有没有选中笔来判断有没有选中橡皮，就是看笔上面的对号

**Comment by YujunA** [comment]
嗯嗯，但是在橡皮和选择墨迹之间切换不是很明显。还有，强烈建议添加一个鼠标悬停和按下的效果（就和普通的按钮一样）。

**Comment by WXRIW** [comment]
鼠标的悬停不会做的，因为本软件是针对触摸屏设计的，加上鼠标部分功能会冲突。
目前在忙另外一个项目，应该有开发者回来做这个功能的，这个按下反馈还是比较有用的

**Comment by jiajiaxd** [comment]
我今天看了一下，ZongziTek的那个fork里就有点击反馈
要不单独把点击反馈的代码合并到这个仓库？ @STBBRD

**Comment by kengwang** [comment]
挺简陋的一个反馈
![image](https://user-images.githubusercontent.com/30862240/216807235-394d4c02-ef72-499f-aeff-f04a8e9d4360.png)

**Comment by WXRIW** [comment]
![image](https://user-images.githubusercontent.com/62491584/218143887-388c76d3-423f-43d5-87cb-ca4abac06b3e.png)
现在好看点了，Issue 关闭。
