### ISSUE TITLE
希望可以自动适配电脑边缘

### ISSUE THREAD

**Issue by muqiupika** [WXRIW/Ink-Canvas#42]
工具条无法变成竖直状态，老师在上课时（尤其是播放PPT）工具栏会挡住最下面的字，写不出来，也影响上课时看PPT最下面的字，希望作者可以出一个这样的功能

**Comment by WXRIW** [comment]
竖直界面不是不能做，而是代码变动太大，很麻烦，一开始设计的时候就没有考虑竖直的，如果真想要竖直，Ink Canvas 2.x中是左右两边竖直的

**Comment by WXRIW** [comment]
软件是安装在c盘的，需要你手动调整到d盘

**Comment by WXRIW** [comment]
https://github.com/WXRIW/Ink-Canvas/releases/download/v3.5.0/Ink.Canvas.Ver.3.5.0-release.zip
下载这个，然后直接解压到d盘，就可以了

**Comment by muqiupika** [comment]
太感谢了，麻烦您了

**Comment by WXRIW** [comment]
不客气
