### ISSUE TITLE
幻灯片模式下没有找到翻页按钮！

### ISSUE THREAD

**Issue by suzhouhu** [WXRIW/Ink-Canvas#43]
![111](https://user-images.githubusercontent.com/23079693/213832226-0d12a486-b777-480b-9c58-326ff6d25366.png)
在放映PPT幻灯片时候没有翻页按钮！

**Comment by jiajiaxd** [comment]
我的建议是看看设置里的PowerPoint支持😅



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月21日(周六) 上午9:34
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [WXRIW/Ink-Canvas] 幻灯片模式下没有找到翻页按钮！ (Issue #43)




 

 在放映PPT幻灯片时候没有翻页按钮！

**Comment by suzhouhu** [comment]
![5@41C697HE8HT )FQSOQI8Q](https://user-images.githubusercontent.com/23079693/213844636-1e3efa61-945a-4495-8eed-db0543f60905.png)在设置里面勾选过的，依然没有，而且无法退出！

**Comment by suzhouhu** [comment]
笔细的一头写字，反过来粗的一头是橡皮擦。（希沃白板自己并不支持此功能）！这个也没找到，如何反过来搽！！

**Comment by WXRIW** [comment]
你的 Office 配置问题，与 Ink Canvas 无关
![image](https://user-images.githubusercontent.com/62491584/213844714-04c84ad3-ab6a-47a0-942f-dbf9f94dfc34.png)

**Comment by WXRIW** [comment]
> 笔细的一头写字，反过来粗的一头是橡皮擦。（希沃白板自己并不支持此功能）！这个也没找到，如何反过来搽！！

不同的笔不一样

**Comment by suzhouhu** [comment]
刘鹄中
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WXRIW/Ink-Canvas"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月21日(星期六) 中午1:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [WXRIW/Ink-Canvas] 幻灯片模式下没有找到翻页按钮！ (Issue #43)





 
Closed #43 as completed.
