### ISSUE TITLE
[FR] 实现多步撤销

### ISSUE THREAD

**Issue by jiajiaxd** [WXRIW/Ink-Canvas#46]
如题，比如清屏、墨迹识别都不能撤回了 @kengwang

**Comment by kengwang** [comment]
在识别出来之后可以立即点击撤回进行撤回操作，如果自动识别后进行了书写，则视为确认自动识别操作，将不允许再撤回到未识别状态。
清屏操作是因为内部实现原因，清屏的话会清空所有墨迹，而墨迹撤回是通过清除上一个墨迹来实现的。


________________________________
From: 甲甲 ***@***.***>
Sent: Friday, February 10, 2023 10:56:29 PM
To: WXRIW/Ink-Canvas ***@***.***>
Cc: Kengwang ***@***.***>; Mention ***@***.***>
Subject: [WXRIW/Ink-Canvas] 新版本的多步撤回无法撤回程序做出的笔迹 (Issue #46)


如题，比如清屏、墨迹识别都不能撤回了 @kengwang<https://jpn01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkengwang&data=05%7C01%7C%7Ccc5d9bdce0114b5d90ac08db0b76fe1b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638116377928849732%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=p7HAy0W5J%2B5GkNoqDX1KkMovwToPlT1yqIunmLlv2Sg%3D&reserved=0>

―

**Comment by WXRIW** [comment]
我觉得吧，还是之前那样比较好，如果不能撤销撤回，那么多步撤回的意义就不大了。现在清屏了也不能撤回了，就比较影响使用了。

**Comment by WXRIW** [comment]
已 Revert，后期会开发完整的多部撤回功能。

**Comment by kengwang** [comment]
https://sharegpt.com/c/frFFtH6

ChatGPT 给出了部分示例代码
