### ISSUE TITLE
请求加回橡皮擦

### ISSUE THREAD

**Issue by jiajiaxd** [WXRIW/Ink-Canvas#5]
橡皮擦3.0版本没了
选择功能有bug

**Comment by WXRIW** [comment]
目前还在想可行方案，可以暂时用旧版，因为我们学校的设备都是支持获取触摸面积的，所以就暂时没做橡皮选项
选择功能的bug希望能描述得更详细些

**Comment by jiajiaxd** [comment]
选择功能问题是用了之后 再用笔就写不出字
需要重新隐藏显示画板

**Comment by WXRIW** [comment]
是触摸屏吗

**Comment by jiajiaxd** [comment]
是触摸屏

**Comment by jiajiaxd** [comment]
emmm橡皮擦的解决方案可以稍微催一下嘛...
这个功能还是很需要的 比较喜欢3.0的新UI

**Comment by WXRIW** [comment]
> emmm橡皮擦的解决方案可以稍微催一下嘛... 这个功能还是很需要的 比较喜欢3.0的新UI

选择功能确实有bug，但是由于再现困难，目前仍在努力修复
下周期中，考完第一时间来解决橡皮擦问题，感谢支持

**Comment by jiajiaxd** [comment]
好的 感谢



---原始邮件---
发件人: "XY ***@***.***&gt;
发送时间: 2021年11月13日(周六) 晚上11:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [WXRIW/Ink-Canvas] 请求加回橡皮擦 (Issue #5)




  
emmm橡皮擦的解决方案可以稍微催一下嘛... 这个功能还是很需要的 比较喜欢3.0的新UI
  
选择功能确实有bug，但是由于再现困难，目前仍在努力修复
 下周期中，考完第一时间来解决橡皮擦问题，感谢支持

**Comment by WXRIW** [comment]
已加回
