### ISSUE TITLE
[Porposal] 快捷键支持

### ISSUE THREAD

**Issue by kengwang** [WXRIW/Ink-Canvas#53]
支持使用快捷键来切换书写状态

需要进行快捷键的操作:

* 笔迹模式切换
* 橡皮
* 回退笔画
* 使用形状

Linked Branch:  [feat/accelerate-key](https://github.com/WXRIW/Ink-Canvas/tree/feat/accelerate-key)

**Comment by kengwang** [comment]
`Ctrl`+`Z`: 撤销上一个笔迹
`Alt`+`D` : 切换输入模式
`Alt`+`S` : 切换输鼠标模式
`Alt`+`E`: 切换橡皮
`Alt`+`L`: 使用直线形状工具

**Comment by shw1395** [comment]
ESC 不是退出快捷键？必须要点设置--立即退出？
