### ISSUE TITLE
增强屏幕画笔功能💕

### ISSUE THREAD

**Issue by Benjamin-Watson0** [WXRIW/Ink-Canvas#56]
咱这个软件儿好像是主打白板的，我觉得屏幕画笔功能比较欠缺，开发大大有空可以搞成Epic Pen那种吗，我觉得他挺好。
个人需求，不合理可以关闭😁。
Epic Pen 官网：https://epicpen.com/

**Comment by WXRIW** [comment]
目前已经能满足课堂教学需求，如有其他需求，可以提具体一点

**Comment by Benjamin-Watson0** [comment]
下面这2个都是我个人的使用场景哈，不是典型教学场景哈。😊
1.截屏像winsows系统截屏那样可以选择自由大小位置截屏，并复制到剪切板，触摸屏截屏挺不方便的，因为没有快捷键。
2. 这个点击笑脸展开的方向提供多个方向，比如，向左弹，向上弹，向下弹，我右撇子觉得总去左边点那个笑脸儿，挺不得劲儿的。这样多个方向的话，也可以把它放在右上角或者有下一点儿，方便使用。

**Comment by WXRIW** [comment]
1. 截屏windows自带的够用了，画板里的截屏只是方便一键截屏用的，如果加上区域框选，那就多了两个步骤了
2. 这个之前有用户提出来过，但是由于实现起来比较复杂，就一直没做。因为当初设计的时候没有考虑到竖向排列，所以改起来工作量很大。以后应该会加入这个功能

**Comment by Benjamin-Watson0** [comment]
第一个需求。我其实是想买那种windows二合一产品,surface平板快速截屏，只能通过一些物理按钮的方式截屏，比如按下触控笔的按钮（这还得占用一个笔快捷键，还得必须有一个笔），或者按住surface的电源键，再或者将截图工具的快捷方式固定在任务栏。我觉得都不太好。😢
第二个需求就还好
________________________________
发件人: XY Wang ***@***.***>
发送时间: 2023年2月24日 15:41
收件人: WXRIW/Ink-Canvas ***@***.***>
抄送: Benjamin Watson ***@***.***>; Author ***@***.***>
主题: Re: [WXRIW/Ink-Canvas] 增强屏幕画笔功能💕 (Issue #56)


  1.  截屏windows自带的够用了，画板里的截屏只是方便一键截屏用的，如果加上区域框选，那就多了两个步骤了
  2.  这个之前有用户提出来过，但是由于实现起来比较复杂，就一直没做。因为当初设计的时候没有考虑到竖向排列，所以改起来工作量很大。以后应该会加入这个功能

**Comment by WXRIW** [comment]
> 还有个小需求：切换至鼠标时能否提供保留屏幕墨迹的选项。提供隐藏和显示屏幕墨迹的切换选项？🥰

目前的两个模式是鼠标模式和画板模式（而不是编辑模式），所以退出画板模式后画板自然就会消失。你说的我能理解，但是实现起来并且还不能有bug，工作量极大

**Comment by WXRIW** [comment]
> 第一个需求。我其实是想买那种windows二合一产品,surface平板快速截屏，只能通过一些物理按钮的方式截屏，比如按下触控笔的按钮（这还得占用一个笔快捷键，还得必须有一个笔），或者按住surface的电源键，再或者将截图工具的快捷方式固定在任务栏。我觉得都不太好。😢
> 
> 这篇文章介绍的surface pro截屏方式https://www.apeaksoft.com/zh-CN/recorder/how-to-screenshot-on-surface-pro.html
> 
> 第二个需求就还好
> 
> ________________________________
> 
> 发件人: XY Wang ***@***.***>
> 
> 发送时间: 2023年2月24日 15:41
> 
> 收件人: WXRIW/Ink-Canvas ***@***.***>
> 
> 抄送: Benjamin Watson ***@***.***>; Author ***@***.***>
> 
> 主题: Re: [WXRIW/Ink-Canvas] 增强屏幕画笔功能💕 (Issue #56)
> 
> 
> 
> 
> 
>   1.  截屏windows自带的够用了，画板里的截屏只是方便一键截屏用的，如果加上区域框选，那就多了两个步骤了
> 
>   2.  这个之前有用户提出来过，但是由于实现起来比较复杂，就一直没做。因为当初设计的时候没有考虑到竖向排列，所以改起来工作量很大。以后应该会加入这个功能
> 
> 
> 
> —
> 
> Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWXRIW%2FInk-Canvas%2Fissues%2F56%23issuecomment-1442972159&data=05%7C01%7C%7C2cfaca63ab844e9f78e108db163a91e7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638128213106346932%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WQmOvBqdCo0o%2FdBfGXO2WAq%2FrnfBHZXshwPartJRWTA%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA22B2SZJVBMKIRSTQIELW5DWZBQ3LANCNFSM6AAAAAAVGQDP6I&data=05%7C01%7C%7C2cfaca63ab844e9f78e108db163a91e7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638128213106346932%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JDsDXg2ob8rnrGYCr7egVFNIxf%2BBJStYxMsgmr%2BzG9A%3D&reserved=0>.
> 
> You are receiving this because you authored the thread.Message ID: ***@***.***>
> 
> 

用笔按键就挺好的，或者屏幕右侧向左滑动，在操作中心有截图，但是11里没有了

**Comment by YujunA** [comment]
> > 还有个小需求：切换至鼠标时能否提供保留屏幕墨迹的选项。提供隐藏和显示屏幕墨迹的切换选项？🥰
> 
> 目前的两个模式是鼠标模式和画板模式（而不是编辑模式），所以退出画板模式后画板自然就会消失。你说的我能理解，但是实现起来并且还不能有bug，工作量极大

这个可以考虑更改相关控件 IsHitTestVisible 的值来实现，我之前做 InkCanvas 就这样弄的。

**Comment by kengwang** [comment]
![image](https://user-images.githubusercontent.com/30862240/230011799-45b687a7-f3b6-41b1-8920-efd396c89f5d.png)

感谢, 似乎有效
