### ISSUE TITLE
关闭 PPT 开启时跳转

### ISSUE THREAD

**Issue by WXRIW** [WXRIW/Ink-Canvas#63]
提供开启此功能的选项，并默认关闭（PowerPoint 默认有此功能）
此外，有用户反馈该消息框可能会弹出多次。

**Comment by CN-Ironegg** [comment]
PowerPoint 自带的太不显眼了，讲真

**Comment by WXRIW** [comment]
是这样的，所以得有，但是默认最好是关闭的

**Comment by jiajiaxd** [comment]
支持提高配置项关闭
