### ISSUE TITLE
能否取消程序运行后自动开启专注助手

### ISSUE THREAD

**Issue by jiajiaxd** [WXRIW/Ink-Canvas#69]
或者把专注助手模式改成优先级应用
现在感觉太侵入了，直接修改电脑设置了

**Comment by WXRIW** [comment]
尊敬的用户您好。

感谢您联系 Ink Canvas 技术支持。我是 Wang，很高兴为您服务。

Ink Canvas 是全屏应用，默认情况下，当有全屏应用时，Windows 会自动进入专注模式。
建议联系 Microsoft 解决此问题，感谢您对 Ink Canvas 的支持！

XY Wang | Ink Canvas Issues 支持服务 | 邮箱地址：[wxriw@foxmail.com](mailto:wxriw@foxmail.com)

我们的服务时间为星期一至星期五（公众假期除外）上午9:00到下午6:00。

**Comment by clover-yan** [comment]
[个人解答](https://github.com/clover-yan)

<br />

您好，我是 Clover Yan，欢迎询问 Ink Canvas Community，很高兴为您提供技术支持。

您可尝试前往“设置”，搜索“专注助手”并取消“在全屏状态下启用专注助手”，以避免 Windows 自动开启专注助手。

<small>[The following is not part of the reply 以下不是回复内容]
我不是微软员工或客服工作人员，回复时间将在24小时内。
I am not a Microsoft employee or customer service agent, the response time will be within 24 hours.</small>

---

**这条评论对你有帮助吗？**
