### ISSUE TITLE
完善对 WPS Office 的支持

### ISSUE THREAD

**Issue by xrgzs** [WXRIW/Ink-Canvas#71]
完善对 WPS Office 的支持

虽然 WPS Office 之前确实存在一些问题，但是现在这些问题已经被逐步修复了。实测 Ink Canvas 搭配新版 WPS Office 已经不会像提示里说的那样“关闭时卡顿”了，但存在几个问题：

1. 先打开 PPT，放映，此时正常显示 PPT 工具，退出后，重新打开 PPT，第一次放映时没有显示 PPT 工具，第二次甚至第三次才正常；
2. 设置里面启用“WPS Office 支持”，重启软件后，“WPS Office 支持”没有被启用；
3. 设置里面的“允许使用手指手势进行幻灯片翻页”在 WPS Office 下没有生效，加上新版 WPS 演示又换回了点击翻页， Ink Canvas 的这个功能会很有用处。

我们这边基本都在使用 WPS Office，为了使用此工具部署 MS Office 不太现实。希望能够尽快处理一下上述几个问题，这样 Ink Canvas 对 WPS Office 的支持也就能够趋于完美了。如果没有大问题，可以默认启用“WPS Office 支持”。

附相关软件版本：
> Windows 10 21H2 x64
> WPS Office 2023 春季更新 14309
> Ink Canvas 画板 3.7.0

**Comment by WXRIW** [comment]
1. 这个问题由 WPS Office 导致，需要有WPS 修复，我们也无能为力。
2. 按照你的说法，后期我们会将这个设置做记忆处理。
3. 你是否有尝试过在 Microsoft Office 中使用此功能？是否像你想象的那样工作？这个功能与 WPS 还是 Office 无关，我怀疑是你没有正确理解这个功能。

**Comment by xrgzs** [comment]
> 1. 这个问题由 WPS Office 导致，需要由 WPS 修复，我们也无能为力。
> 2. 按照你的说法，后期我们会将这个设置做记忆处理。
> 3. 你是否有尝试过在 Microsoft Office 中使用此功能？是否像你想象的那样工作？这个功能与 WPS 还是 Office 无关，我怀疑是你没有正确理解这个功能。

1. 第一个问题今天我又反复测试了一下，发现没有我之前说的那么严重，PPT放映状态翻一两页以后，Ink Canvas就可以正常切换到PPT模式了，这个确实是WPS的问题，但是综上所述在实际使用中其实影响不大，您也不用太在意；
2. 您能对此问题作出回应，并有计划后期要进行修复，在此我表示十分欣慰，也希望您可以抽出您宝贵的时间尽快修复一下；
3. 很抱歉，这个功能我确实没有正确理解其用法，给您带来了麻烦，请谅解。

再次感谢您能够给我们带来如此好用的批注工具，愿Ink Canvas能越来越好！！！
