### ISSUE TITLE
移动／缩放画布之后再撤销会导致恢复的笔迹在不正确的位置

### ISSUE THREAD

**Issue by clover-yan** [WXRIW/Ink-Canvas#75]
## 复现步骤
1. 进入画板模式；
2. 在画布上绘画；
3. 使用橡皮擦除部分笔迹；
4. 移动／缩放画布；
5. 使用撤销↩️功能；
6. 笔迹被恢复到错误的位置。

## 解决方案
有两种解决方案：
1. 在 TimeMachine 中按照与画布的相对位置记录和恢复笔迹。
2. 将画布缩放事件也记入 TimeMachine 中。

**Comment by Raspberry-Monster** [comment]
Fixed
