### ISSUE TITLE
添加可选择默认擦除方式的选项

### ISSUE THREAD

**Issue by CN-Ironegg** [WXRIW/Ink-Canvas#79]
可设三个选项：

1. 默认点橡皮
2. 默认线橡皮
3. 图标切换模式

**Comment by kengwang** [comment]
assign to @kengwang


________________________________
From: Netherite_Bowl ***@***.***>
Sent: Saturday, July 15, 2023 9:23:02 AM
To: WXRIW/Ink-Canvas ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [WXRIW/Ink-Canvas] 添加可选择默认擦除方式的选项 (Issue #79)


可设三个选项：

  1.  默认点橡皮
  2.  默认线橡皮
  3.  图标切换模式

―

**Comment by kengwang** [comment]
晚上弄

**Comment by clover-yan** [comment]
@kengwang 调节此选项似乎并不影响使用手指触摸屏幕时的橡皮行为，希望能够修改逻辑或提供另外的选项控制。

目前用手指触摸屏幕仍然是交替切换面积擦 / 墨迹擦，极为不方便。

**Comment by CN-Ironegg** [comment]
Pull #72 确实修复了橡皮问题，且 _**交 <del>叉</del> 替切换**_ 不宜作为默认选项

另附交叉改成交替的理论支持

> 词语 | 交替
拼音 | jiāo tì 
解释 | ①接替：新旧～。 
②替换着；轮流：循环～ㄧ儿童的作业和休息应当～进行

>词语 | 交叉
拼音 | jiāo chā 
解释 | ①几个方向不同的线条或线路互相穿过：～火力网 ㄧ立体～桥 ㄧ公路和铁路～。 
②有相同有不同的；有相重的：～的意见 ㄧ～学科 
③间隔穿插：～作业。
