### ISSUE TITLE
功能请求：多步撤回的补充

### ISSUE THREAD

**Issue by jiajiaxd** [WXRIW/Ink-Canvas#85]
多步撤回无法撤回 放大/缩小、自动识别图形 希望可以改进。

**Comment by clover-yan** [comment]
对于第一个问题，#75 中已有反馈，等待修复；

对于第二个问题，仓库内最新版本已经修复，请更新到最新 `master` 分支版本（在 [Actions](https://github.com/WXRIW/Ink-Canvas/actions) 页面最新编译结果中 Artifacts 下点击下载 `Ink-Canvas` 并覆盖到安装目录）即可解决。

**Comment by jiajiaxd** [comment]
好的
