### ISSUE TITLE
[紧急] 希沃课堂助手导致自动查杀 PPT 小工具失效

### ISSUE THREAD

**Issue by clover-yan** [WXRIW/Ink-Canvas#87]
## 情况说明
近日，希沃 PPT 小工具云控更新为希沃课堂助手（`SeewoIwbAssistant.exe`）导致自动查杀失效，工具栏叠加显示影响使用。

## 解决方案
暂时卸载希沃课堂助手。

## 修复方式
暂无，因为希沃课堂助手有保活，难以查杀。

**Comment by kengwang** [comment]
感谢反馈，将会尽快适配


________________________________
From: clover_yan ***@***.***>
Sent: Friday, September 22, 2023 12:12:08 PM
To: WXRIW/Ink-Canvas ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [WXRIW/Ink-Canvas] [紧急] 希沃课堂助手导致自动查杀 PPT 小工具失效 (Issue #87)


情况说明

近日，希沃 PPT 小工具云控更新为希沃课堂助手（SeewoIwbAssistant.exe）导致自动查杀失效，工具栏叠加显示影响使用。

解决方案

暂时卸载希沃课堂助手。

修复方式

暂无，因为希沃课堂助手有保活，难以查杀。

―
