### ISSUE TITLE
建议新版本将黑板功能图标调整为类似此图标的，降低使用门槛

### ISSUE THREAD

**Issue by jiajiaxd** [WXRIW/Ink-Canvas#9]
![image](https://user-images.githubusercontent.com/51043917/145718864-b9641c00-c4ec-4f41-b963-0fadbcd713fd.png)
这种更加明了，一看就知道是画板功能
天知道某些年龄大的老师打开画板有多困难(

还有建议添加深绿色的黑板，太阳大照到屏幕上黑色背景容易反光学生看不清= =

**Comment by WXRIW** [comment]
做不了多色，并且今天起停止新功能更新。
没有用深绿色是因为希沃白板用的是深绿色，而我不喜欢希沃白板。
目前这个黑色不是纯黑，而是选择了跟微软白板一致的黑色。
