### ISSUE TITLE
撤销相关问题

### ISSUE THREAD

**Issue by NetheriteBowl** [WXRIW/Ink-Canvas#93]
多笔书写后使用橡皮再点击隐藏画板按钮（开启 **“切换到鼠标模式自动清屏“** 情况下）重新回到画笔模式，点击撤销。发现恢复了擦除的部分，而其他内容不会恢复

详见下面的gif录屏

**Comment by CN-Ironegg** [comment]
_如果描述不够具体，待周六放假详细叙述_

**Comment by CN-Ironegg** [comment]
![1](https://github.com/WXRIW/Ink-Canvas/assets/75211294/032ae493-d7fa-4f44-a1be-08ac5422bb2e)

**Comment by kengwang** [comment]
此问题目测为 TimeMachine  问题
assign to @Raspberry-Monster

**Comment by CN-Ironegg** [comment]
> 避免此问题的方法：
> 
> 先点击颜色（退出橡皮模式），再退出画板。

问题场景：误触后尝试恢复笔迹

**Comment by CN-Ironegg** [comment]
![2](https://github.com/WXRIW/Ink-Canvas/assets/75211294/bc3beaea-93af-4c0b-8d6d-0044d1e1c4ca)
同源问题

**Comment by clover-yan** [comment]
## 可能的修复方式
清屏前先切换到书写模式。

**Comment by NetheriteBowl** [comment]
#114 已经修复了该问题

**Comment by clover-yan** [comment]
> #114 已经修复了该问题

@NetheriteBowl 其实不用手动关闭议题，当拉取请求得到合并之后，被 `fix`、`close`、`resolve` 等标记的议题会被自动关闭。 参考 [Linking a pull request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)。

**Comment by NetheriteBowl** [comment]
> > #114 已经修复了该问题
> 
> @NetheriteBowl 其实不用手动关闭议题，当拉取请求得到合并之后，被 `fix`、`close`、`resolve` 等标记的议题会被自动关闭。 参考 [Linking a pull request to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)。

学到了
