### ISSUE TITLE
在白板模式内开始放映 PPT 会导致各种问题

### ISSUE THREAD

**Issue by clover-yan** [WXRIW/Ink-Canvas#94]
## 存在的问题

- [ ] 窗口不会置顶，引入自 #66。
- [x] 新书写的墨迹会丢失。
- [ ] 退出放映之后，工具栏会重新定位到不正确的位置。
- [ ] ……（请帮助测试）

## 复现方式
1. 进入白板；
2. 用快捷键 `Alt` + `Tab` 切换到 PPT 界面，开始放映。

## 可能的修复方式
白板内进入放映时，先退出白板，再进入放映模式。

**Comment by kengwang** [comment]
放映开始的话先退出白板模式再进入放映模式似乎是个有效的方法

**Comment by clover-yan** [comment]
@kengwang 经过测试发现没能置顶，并且退出放映之后工具栏重新定位到了不正确的位置。
