### ISSUE TITLE
在截图时获取和使用实际屏幕尺寸

### ISSUE THREAD

**Issue by clover-yan** [WXRIW/Ink-Canvas#97]
在截图时获取和使用实际屏幕尺寸，以便在使用「系统」选项替代高 DPI 缩放设置时正确截图。
使用「系统」选项替代高 DPI 缩放设置能够提升性能，但会导致截图区域不正确。

相关代码行见 <https://github.com/WXRIW/Ink-Canvas/blob/da359cd3f80f55586e309317b91abe0b6436b84f/Ink%20Canvas/MainWindow.xaml.cs#L6669C23-L6669C23>。

**Comment by Raspberry-Monster** [comment]
Fixed
